### ISSUE TITLE
2 question

### ISSUE THREAD

**Issue by rimac3** [SharafatKarim/WebsiteAsApp#1]
1.Does this support javascript "localStorage"?

2.How to make the back button  function to exit the app instead of returning to the history page?

**Comment by SharafatKarim** [comment]
1) As this is an open source project, I tried to keep it minimal. But you can enable storage like,
```java
        webSettings.setAllowContentAccess(true);
        webSettings.setAllowFileAccess(true);
        webSettings.setDomStorageEnabled(true);
```
> For more information, please refer to this [thread](https://stackoverflow.com/questions/45582243/why-cant-i-access-localstorage-in-a-string-variable-on-android-studio).

2) Just remove the `onBackPressed` overrided method to do so from `MainActivity.java`,
```java
@Override
    public void onBackPressed() {
        if (webView.canGoBack()) {
            webView.goBack();
        } else {
            super.onBackPressed();
        }
    }
```
