### ISSUE TITLE
Build Problem (R does not exist)

### ISSUE THREAD

**Issue by osmanbilir** [SharafatKarim/WebsiteAsApp#2]
Hello, I am very new to this, please excuse my inexperience.
"**com.sharafat.website**" in the "**namespace**=" and "**applicationId**=" fields in the "**build.gradle.kts**" file in the project
and I replaced the "**versionCode**=" and "**versionName**=" fields. 

When I want to build, I get "**C:\Users\....\app\src\main\java\com\sharafat\website\MainActivity.java:30: error: package R does not exist setContentView(R.layout.activity_main);** " I get an error.

How can I get over this?
What I want to do is to extract the project as aab and apk and send it to GooglePlay.
Thank you.

**Comment by SharafatKarim** [comment]
Sorry, brother, you actually can't just change fields in `build.gradle`. You have to refactor it, actually. So I'll recommend you to create a new project in android studio, then copy and paste my codes as required. 

Or, if you want to directly change, please refer to,
- [Rename package in Android Studio](https://stackoverflow.com/questions/16804093/rename-package-in-android-studio)
